LEADS = [
  dict(slug="build-pro-mechanical", name="Build-Pro Mechanical LLC", short="Build-Pro",
       cat="hvac", market="Austin / Elgin, TX", phone="(512) 955-5689", phone_tel="+15129555689",
       website="https://buildpromechanical.com/",
       address="18300 Basket Flower Bend, Elgin, TX 78621",
       tagline="Cool homes. Honest HVAC. Same-day when Austin heats up.",
       blurb="Family-owned Build-Pro handles heating, cooling, and commercial systems across Austin & Elgin — free estimates, all makes & models, transparent pricing.",
       services=[
         ("Heating repair & tune-ups", "Furnaces and heat pumps restored before the cold front hits."),
         ("AC repair & installs", "Same-day cooling service when Central Texas temperatures spike."),
         ("Commercial HVAC", "Keep offices and shops comfortable without drama."),
         ("Indoor air quality", "Filtration and airflow upgrades for healthier rooms."),
       ],
       proofs=["Family owned & operated", "Free estimates", "All makes & models", "Same-day service"],
       h2_services="Heating & cooling, handled properly",
       h2_proof="Why Austin homeowners call Build-Pro",
       cta="Call for same-day service", scrape_ok=True),
  dict(slug="bank-dental", name="Bank Dental Practice", short="Bank Dental",
       cat="dental", market="Prestwich, Greater Manchester", phone="0161 798 9955", phone_tel="+441617989955",
       website="https://bankdentalpractice.co.uk/",
       address="437 Bury New Road, Prestwich, Manchester M25 1AF",
       tagline="Private dentistry on Bury New Road — calm, modern, welcoming.",
       blurb="Independent private practice since 1984. Invisalign, implants, whitening, composite artistry, and EMS Airflow hygiene. New patients welcome.",
       services=[
         ("Private check-ups & care", "Unhurried examinations and preventive dentistry."),
         ("Invisalign & Angel Aligners", "Discreet straightening planned around your lifestyle."),
         ("Smile cosmetics", "Bonding, veneers, and professional whitening."),
         ("Implants & restorative", "Rebuild comfort and confidence with lasting work."),
       ],
       proofs=["Fully private", "New patients welcome", "EMS Airflow", "Prestwich since 1984"],
       h2_services="Treatments patients actually ask for",
       h2_proof="A Prestwich practice built on trust",
       cta="Book a consultation",
       hours="Mon & Thu 8–5 · Tue 8–7 · Wed 8–4:30 · Fri 8–2:30",
       scrape_ok=False,
       scrape_note="Direct scrape 403/401; rebuilt from public CQC + indexed practice pages."),
  dict(slug="omega-mp-autobody", name="Omega MP Autobody", short="Omega MP",
       cat="auto", market="Toronto, ON — The Junction", phone="(416) 769-5341", phone_tel="+14167695341",
       website="https://www.mpautobody.ca/",
       address="353 Ryding Avenue, Toronto, ON M6N 1H6",
       email="info@mpautobody.ca",
       tagline="Top-rated collision work. Affordable out-of-pocket rates.",
       blurb="30+ years in Toronto’s west end. Insurance claims, paint matching, lease returns, fleet work, and 24/7 towing — quality you can feel in the finish.",
       services=[
         ("Insurance claims", "We work with every insurer and keep the paperwork moving."),
         ("Dents, bumpers & scratches", "Collision and cosmetic repairs done once, done right."),
         ("Expert paint matching", "Factory-true colour for a finish that disappears."),
         ("24/7 towing & support", "Accident help on the shop line, day or night."),
       ],
       proofs=["30+ years", "Insurance approved", "Free estimates", "24/7 towing"],
       h2_services="Collision & cosmetic repairs",
       h2_proof="Junction drivers already know",
       cta="Get a free estimate", hours="Mon–Thu 8–5 · Fri 8–4", scrape_ok=True),
  dict(slug="hawthorn-vets", name="Hawthorn Veterinary Clinic", short="Hawthorn Vets",
       cat="vet", market="Hawthorn, Melbourne VIC", phone="03 9818 7818", phone_tel="+61398187818",
       website="https://www.hawthornvets.com.au/",
       address="200 Auburn Rd, Hawthorn VIC 3122",
       tagline="Independent vet care for the pets you worry about at 2am.",
       blurb="Owned by Dr Trevor Cannell & Dr Sharon Rowland — not a corporate chain. Consults, surgery, dentistry, and vaccines for Hawthorn, Kew, Canterbury & Toorak.",
       services=[
         ("Consultations by appointment", "Proper time with the vet — mornings, afternoons, evenings."),
         ("Vaccinations & health checks", "Lifestyle-tailored vaccines after a full exam."),
         ("Surgery with careful monitoring", "Weekday procedures, modern equipment, strong pain relief."),
         ("Dentistry & diagnostics", "Dental care, radiography, pathology, microchipping."),
       ],
       proofs=["Independent / non-corporate", "Local owner-vets", "Est. lineage 1970s", "Sat morning clinics"],
       h2_services="Care for every life stage",
       h2_proof="Why Hawthorn families stay",
       cta="Call to book", hours="Mon–Fri 8am–7pm · Sat 9am–11am", scrape_ok=True),
  dict(slug="bacharach-law", name="Bacharach Law", short="Bacharach Law",
       cat="legal", market="Denver, CO", phone="(720) 303-5778", phone_tel="+17203035778",
       website="https://bacharach.law/",
       address="130 W. 5th Ave, Denver, CO 80204",
       email="william@bacharach.law",
       tagline="When everything is on the line, fight back.",
       blurb="Criminal defense attorney William Bacharach — DUI, drug crimes, assault, domestic violence, and veterans law across the Front Range. Free consultation. Available 24/7.",
       services=[
         ("DUI & DWAI defense", "Colorado DUI strategy from first call to courtroom."),
         ("Drug crime defense", "Possession and related charges with a clear plan."),
         ("Assault & violent crimes", "Misdemeanor and felony defense handled carefully."),
         ("Veterans law", "VA-accredited counsel for veterans in crisis."),
       ],
       proofs=["Free consultation", "Front Range", "VA-accredited", "Available 24/7"],
       h2_services="Criminal defense across Colorado",
       h2_proof="What you get with Bacharach",
       cta="Request a free consult", scrape_ok=True),
  dict(slug="blooming-moon-spa", name="Blooming Moon Wellness Spa", short="Blooming Moon",
       cat="spa", market="Overlook, Portland OR", phone="(971) 279-2757", phone_tel="+19712792757",
       website="https://www.bloomingmoonspa.com/",
       address="1417 N. Shaver St, Portland, OR 97227",
       email="contact@bloomingmoonspa.com",
       tagline="Skin, steam, and stillness in Overlook Village.",
       blurb="Vegan-friendly, cruelty-free spa rituals — facials, massage, sauna soak + steam, lashes, and seasonal treatments a short walk from Overlook Park MAX.",
       services=[
         ("Facials & skin peels", "Individualized facial care with thoughtful product lines."),
         ("Massage & body treatments", "Hands-on work that resets a Portland week."),
         ("Sauna, soak + steam", "Heat and recovery without leaving the neighborhood."),
         ("Beauty details", "Nails, lashes, brows, and gentle hair removal."),
       ],
       proofs=["Overlook Village", "Vegan-friendly", "Tue–Sun 10–8", "Free street parking"],
       h2_services="Rituals for skin, body & breath",
       h2_proof="The Overlook neighborhood spa",
       cta="Book your visit", hours="Tue–Sun 10am–8pm · Closed Mondays", scrape_ok=True),
  dict(slug="kuhn-plumbing", name="Kuhn Plumbing", short="Kuhn Plumbing",
       cat="plumbing", market="Chicago, IL", phone="(773) 525-0474", phone_tel="+17735250474",
       website="https://kuhnplumbing.com/",
       address="Chicago, IL",
       tagline="Chicago plumbing since 1908 — still family, still on call.",
       blurb="A century of Chicago craft. Emergency repairs, drain cleaning, water heaters, gas lines, and remodeling from a crew that treats your home like theirs.",
       services=[
         ("Emergency plumbing", "When pipes fail at the worst moment, we’re ready."),
         ("Drain & sewer cleaning", "Clear lines before a clog becomes a flood."),
         ("Water heater service", "Repair and replacement so hot water returns fast."),
         ("Remodel & specialty work", "Baths, gas lines, sump/ejector pumps, fixtures."),
       ],
       proofs=["Since 1908", "Family-owned", "Chicago local", "Emergency ready"],
       h2_services="Plumbing problems we solve daily",
       h2_proof="Four generations of Chicago trust",
       cta="Get an estimate", scrape_ok=True),
  dict(slug="nations-dental", name="Nations Dental Studio", short="Nations Dental",
       cat="dental", market="West Nashville, TN", phone="(615) 933-5800", phone_tel="+16159335800",
       website="https://nationsdentalstudio.com/",
       address="4900 Centennial Blvd, Suite 104, Nashville, TN 37209",
       email="hello@nationsdentalstudio.com",
       tagline="Honest dentistry you can feel great about.",
       blurb="Woman-owned studio led by Dr. Diana D'Aoust in The Nations. Cosmetic, restorative, and emergency care — 507+ five-star Google reviews and transparent treatment plans.",
       services=[
         ("Cosmetic dentistry", "Invisalign, whitening, veneers, smile makeovers."),
         ("Restorative care", "Implants, crowns, bridges, and dentures."),
         ("General & emergency", "Cleanings, exams, fillings, same-day urgent care."),
         ("Calm visits", "Easy scheduling, sedation options, studio atmosphere."),
       ],
       proofs=["507+ five-star reviews", "Woman-owned", "The Nations", "Transparent care"],
       h2_services="Your smile, planned with honesty",
       h2_proof="Why Nashville patients stay",
       cta="Book online / call", scrape_ok=True),
  dict(slug="capstone-solicitors", name="Capstone Solicitors", short="Capstone",
       cat="legal", market="Bishopston, Bristol", phone="0117 942 8214", phone_tel="+441179428214",
       website="https://www.capstonelaw.co.uk/",
       address="62 Gloucester Road, Bristol BS7 8BH",
       email="enquiries@capstonelaw.co.uk",
       tagline="Independent Bristol solicitors. Your work, done by lawyers.",
       blurb="Christian ethos, lineage to 1973 on Gloucester Road. Residential & commercial conveyancing plus wills, trusts & estates — handled by qualified practising lawyers, not support staff.",
       services=[
         ("Residential conveyancing", "Buying and selling with clear, careful progress."),
         ("Commercial conveyancing", "Property work for businesses that need certainty."),
         ("Wills, trusts & estates", "Planning and administration with integrity."),
         ("Approachable counsel", "Friendly guidance for family and business goals."),
       ],
       proofs=["Independent", "Lineage 1973", "Qualified lawyers only", "SRA regulated"],
       h2_services="Legal services from Gloucester Road",
       h2_proof="How Capstone works differently",
       cta="Contact the firm", scrape_ok=True),
  dict(slug="quality-air", name="Quality Air", short="Quality Air",
       cat="hvac", market="Brisbane & SEQ", phone="07 3395 7633", phone_tel="+61733957633",
       website="https://www.qualityac.com.au/",
       address="66 Riverside Place, Morningside QLD 4170",
       tagline="Air conditioning Brisbane trusts since 1988.",
       blurb="Family HVAC — Dad and three sons. Ducted and split installs, servicing, and commercial work across Brisbane, Gold Coast, and Sunshine Coast.",
       services=[
         ("Ducted air conditioning", "Whole-home comfort designed and installed properly."),
         ("Split system specialists", "Efficient room and multi-split installs & repairs."),
         ("Servicing & maintenance", "Keep systems efficient, quiet, and lasting longer."),
         ("Commercial HVAC", "Business installs and maintenance across SEQ."),
       ],
       proofs=["Family since 1988", "Free install quotes", "Brisbane · GC · Sunshine Coast", "Residential & commercial"],
       h2_services="Brisbane air conditioning, end to end",
       h2_proof="A family firm that shows up",
       cta="Get a free quote", hours="Mon–Fri 8:30am–4pm", scrape_ok=True),
]

PROTECTED = {
    "kenworthey-law", "levine-law", "heller-org", "365-kool",
    "martys-auto-body", "xl-rpm", "irvine-auto-repair", "wynn-nails",
}

OVERRIDES = {
  "quality-air": {"accent": "#009ADA", "accent2": "#FBBC05"},
  "omega-mp-autobody": {"accent": "#e10600", "accent2": "#1889A6"},
  "nations-dental": {"accent": "#244f6d", "accent2": "#b78f32"},
  "bacharach-law": {"accent": "#1a2744", "accent2": "#2e7a48"},
  "blooming-moon-spa": {"accent": "#6b4570", "accent2": "#c98b96"},
  "build-pro-mechanical": {"accent": "#0b6e4f", "accent2": "#f4a261"},
  "capstone-solicitors": {"accent": "#3d2b1f", "accent2": "#b08d57"},
  "bank-dental": {"accent": "#1b4b6b", "accent2": "#c9a66b"},
  "hawthorn-vets": {"accent": "#2a6f6f", "accent2": "#e9c46a"},
  "kuhn-plumbing": {"accent": "#0d3b66", "accent2": "#f4d35e"},
}

NICHE = {
  "hvac": dict(fonts_href="family=Archivo:wght@500;600;700;800&family=DM+Sans:wght@400;500;600;700",
    font_display='"Archivo", system-ui, sans-serif', font_body='"DM Sans", system-ui, sans-serif',
    bg="#eef3f7", ink="#0c1b2a", muted="#4a5d70", card="#ffffff", accent="#0077a8", accent2="#f0a202"),
  "dental": dict(fonts_href="family=Cormorant+Garamond:wght@500;600;700&family=Manrope:wght@400;500;600;700",
    font_display='"Cormorant Garamond", Georgia, serif', font_body='"Manrope", system-ui, sans-serif',
    bg="#f6f3ee", ink="#1c2b33", muted="#5d6b73", card="#ffffff", accent="#1f5c6b", accent2="#b8894a"),
  "auto": dict(fonts_href="family=Oswald:wght@500;600;700&family=Source+Sans+3:wght@400;600;700",
    font_display='"Oswald", Impact, sans-serif', font_body='"Source Sans 3", system-ui, sans-serif',
    bg="#121212", ink="#f3f3f3", muted="#a8a8a8", card="#1c1c1c", accent="#e10600", accent2="#f5c518"),
  "vet": dict(fonts_href="family=Fraunces:opsz,wght@9..144,500;9..144,700&family=Nunito:wght@400;600;700;800",
    font_display='"Fraunces", Georgia, serif', font_body='"Nunito", system-ui, sans-serif',
    bg="#f3f7f4", ink="#1e3329", muted="#4f6a5a", card="#ffffff", accent="#2f6f5e", accent2="#e2b04a"),
  "legal": dict(fonts_href="family=Libre+Franklin:wght@500;600;700&family=Source+Serif+4:opsz,wght@8..60,500;8..60,700",
    font_display='"Source Serif 4", Georgia, serif', font_body='"Libre Franklin", system-ui, sans-serif',
    bg="#f4f1ea", ink="#1a1a1a", muted="#5a554c", card="#fffcf7", accent="#1a2744", accent2="#b08d57"),
  "spa": dict(fonts_href="family=Cormorant:wght@500;600;700&family=Outfit:wght@300;400;500;600",
    font_display='"Cormorant", Georgia, serif', font_body='"Outfit", system-ui, sans-serif',
    bg="#f7f0f4", ink="#2a2030", muted="#6d5c70", card="#fffafb", accent="#6b4570", accent2="#d4a5b0"),
  "plumbing": dict(fonts_href="family=Barlow+Condensed:wght@600;700;800&family=Barlow:wght@400;500;600;700",
    font_display='"Barlow Condensed", Impact, sans-serif', font_body='"Barlow", system-ui, sans-serif',
    bg="#eef1f5", ink="#0d2137", muted="#4d5d6d", card="#ffffff", accent="#0d3b66", accent2="#f0c43c"),
}
